// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: grpc/proto/wcf.proto

package wcf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Functions int32

const (
	Functions_FUNC_RESERVED         Functions = 0
	Functions_FUNC_IS_LOGIN         Functions = 1
	Functions_FUNC_GET_SELF_WXID    Functions = 16
	Functions_FUNC_GET_MSG_TYPES    Functions = 17
	Functions_FUNC_GET_CONTACTS     Functions = 18
	Functions_FUNC_GET_DB_NAMES     Functions = 19
	Functions_FUNC_GET_DB_TABLES    Functions = 20
	Functions_FUNC_GET_USER_INFO    Functions = 21
	Functions_FUNC_GET_AUDIO_MSG    Functions = 22
	Functions_FUNC_SEND_TXT         Functions = 32
	Functions_FUNC_SEND_IMG         Functions = 33
	Functions_FUNC_SEND_FILE        Functions = 34
	Functions_FUNC_SEND_XML         Functions = 35
	Functions_FUNC_SEND_EMOTION     Functions = 36
	Functions_FUNC_SEND_RICH_TXT    Functions = 37
	Functions_FUNC_SEND_PAT_MSG     Functions = 38
	Functions_FUNC_FORWARD_MSG      Functions = 39
	Functions_FUNC_ENABLE_RECV_TXT  Functions = 48
	Functions_FUNC_DISABLE_RECV_TXT Functions = 64
	Functions_FUNC_EXEC_DB_QUERY    Functions = 80
	Functions_FUNC_ACCEPT_FRIEND    Functions = 81
	Functions_FUNC_RECV_TRANSFER    Functions = 82
	Functions_FUNC_REFRESH_PYQ      Functions = 83
	Functions_FUNC_DOWNLOAD_ATTACH  Functions = 84
	Functions_FUNC_GET_CONTACT_INFO Functions = 85
	Functions_FUNC_REVOKE_MSG       Functions = 86
	Functions_FUNC_DECRYPT_IMAGE    Functions = 96
	Functions_FUNC_EXEC_OCR         Functions = 97
	Functions_FUNC_ADD_ROOM_MEMBERS Functions = 112
	Functions_FUNC_DEL_ROOM_MEMBERS Functions = 113
	Functions_FUNC_INV_ROOM_MEMBERS Functions = 114
)

// Enum value maps for Functions.
var (
	Functions_name = map[int32]string{
		0:   "FUNC_RESERVED",
		1:   "FUNC_IS_LOGIN",
		16:  "FUNC_GET_SELF_WXID",
		17:  "FUNC_GET_MSG_TYPES",
		18:  "FUNC_GET_CONTACTS",
		19:  "FUNC_GET_DB_NAMES",
		20:  "FUNC_GET_DB_TABLES",
		21:  "FUNC_GET_USER_INFO",
		22:  "FUNC_GET_AUDIO_MSG",
		32:  "FUNC_SEND_TXT",
		33:  "FUNC_SEND_IMG",
		34:  "FUNC_SEND_FILE",
		35:  "FUNC_SEND_XML",
		36:  "FUNC_SEND_EMOTION",
		37:  "FUNC_SEND_RICH_TXT",
		38:  "FUNC_SEND_PAT_MSG",
		39:  "FUNC_FORWARD_MSG",
		48:  "FUNC_ENABLE_RECV_TXT",
		64:  "FUNC_DISABLE_RECV_TXT",
		80:  "FUNC_EXEC_DB_QUERY",
		81:  "FUNC_ACCEPT_FRIEND",
		82:  "FUNC_RECV_TRANSFER",
		83:  "FUNC_REFRESH_PYQ",
		84:  "FUNC_DOWNLOAD_ATTACH",
		85:  "FUNC_GET_CONTACT_INFO",
		86:  "FUNC_REVOKE_MSG",
		96:  "FUNC_DECRYPT_IMAGE",
		97:  "FUNC_EXEC_OCR",
		112: "FUNC_ADD_ROOM_MEMBERS",
		113: "FUNC_DEL_ROOM_MEMBERS",
		114: "FUNC_INV_ROOM_MEMBERS",
	}
	Functions_value = map[string]int32{
		"FUNC_RESERVED":         0,
		"FUNC_IS_LOGIN":         1,
		"FUNC_GET_SELF_WXID":    16,
		"FUNC_GET_MSG_TYPES":    17,
		"FUNC_GET_CONTACTS":     18,
		"FUNC_GET_DB_NAMES":     19,
		"FUNC_GET_DB_TABLES":    20,
		"FUNC_GET_USER_INFO":    21,
		"FUNC_GET_AUDIO_MSG":    22,
		"FUNC_SEND_TXT":         32,
		"FUNC_SEND_IMG":         33,
		"FUNC_SEND_FILE":        34,
		"FUNC_SEND_XML":         35,
		"FUNC_SEND_EMOTION":     36,
		"FUNC_SEND_RICH_TXT":    37,
		"FUNC_SEND_PAT_MSG":     38,
		"FUNC_FORWARD_MSG":      39,
		"FUNC_ENABLE_RECV_TXT":  48,
		"FUNC_DISABLE_RECV_TXT": 64,
		"FUNC_EXEC_DB_QUERY":    80,
		"FUNC_ACCEPT_FRIEND":    81,
		"FUNC_RECV_TRANSFER":    82,
		"FUNC_REFRESH_PYQ":      83,
		"FUNC_DOWNLOAD_ATTACH":  84,
		"FUNC_GET_CONTACT_INFO": 85,
		"FUNC_REVOKE_MSG":       86,
		"FUNC_DECRYPT_IMAGE":    96,
		"FUNC_EXEC_OCR":         97,
		"FUNC_ADD_ROOM_MEMBERS": 112,
		"FUNC_DEL_ROOM_MEMBERS": 113,
		"FUNC_INV_ROOM_MEMBERS": 114,
	}
)

func (x Functions) Enum() *Functions {
	p := new(Functions)
	*p = x
	return p
}

func (x Functions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Functions) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_wcf_proto_enumTypes[0].Descriptor()
}

func (Functions) Type() protoreflect.EnumType {
	return &file_grpc_proto_wcf_proto_enumTypes[0]
}

func (x Functions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Functions.Descriptor instead.
func (Functions) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Func  Functions              `protobuf:"varint,1,opt,name=func,proto3,enum=wcf.Functions" json:"func,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Request_Empty
	//	*Request_Str
	//	*Request_Txt
	//	*Request_File
	//	*Request_Query
	//	*Request_V
	//	*Request_M
	//	*Request_Xml
	//	*Request_Dec
	//	*Request_Tf
	//	*Request_Ui64
	//	*Request_Flag
	//	*Request_Att
	//	*Request_Am
	//	*Request_Rt
	//	*Request_Pm
	//	*Request_Fm
	Msg           isRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetFunc() Functions {
	if x != nil {
		return x.Func
	}
	return Functions_FUNC_RESERVED
}

func (x *Request) GetMsg() isRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Request) GetEmpty() *Empty {
	if x != nil {
		if x, ok := x.Msg.(*Request_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *Request) GetStr() string {
	if x != nil {
		if x, ok := x.Msg.(*Request_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Request) GetTxt() *TextMsg {
	if x != nil {
		if x, ok := x.Msg.(*Request_Txt); ok {
			return x.Txt
		}
	}
	return nil
}

func (x *Request) GetFile() *PathMsg {
	if x != nil {
		if x, ok := x.Msg.(*Request_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Request) GetQuery() *DbQuery {
	if x != nil {
		if x, ok := x.Msg.(*Request_Query); ok {
			return x.Query
		}
	}
	return nil
}

func (x *Request) GetV() *Verification {
	if x != nil {
		if x, ok := x.Msg.(*Request_V); ok {
			return x.V
		}
	}
	return nil
}

func (x *Request) GetM() *MemberMgmt {
	if x != nil {
		if x, ok := x.Msg.(*Request_M); ok {
			return x.M
		}
	}
	return nil
}

func (x *Request) GetXml() *XmlMsg {
	if x != nil {
		if x, ok := x.Msg.(*Request_Xml); ok {
			return x.Xml
		}
	}
	return nil
}

func (x *Request) GetDec() *DecPath {
	if x != nil {
		if x, ok := x.Msg.(*Request_Dec); ok {
			return x.Dec
		}
	}
	return nil
}

func (x *Request) GetTf() *Transfer {
	if x != nil {
		if x, ok := x.Msg.(*Request_Tf); ok {
			return x.Tf
		}
	}
	return nil
}

func (x *Request) GetUi64() uint64 {
	if x != nil {
		if x, ok := x.Msg.(*Request_Ui64); ok {
			return x.Ui64
		}
	}
	return 0
}

func (x *Request) GetFlag() bool {
	if x != nil {
		if x, ok := x.Msg.(*Request_Flag); ok {
			return x.Flag
		}
	}
	return false
}

func (x *Request) GetAtt() *AttachMsg {
	if x != nil {
		if x, ok := x.Msg.(*Request_Att); ok {
			return x.Att
		}
	}
	return nil
}

func (x *Request) GetAm() *AudioMsg {
	if x != nil {
		if x, ok := x.Msg.(*Request_Am); ok {
			return x.Am
		}
	}
	return nil
}

func (x *Request) GetRt() *RichText {
	if x != nil {
		if x, ok := x.Msg.(*Request_Rt); ok {
			return x.Rt
		}
	}
	return nil
}

func (x *Request) GetPm() *PatMsg {
	if x != nil {
		if x, ok := x.Msg.(*Request_Pm); ok {
			return x.Pm
		}
	}
	return nil
}

func (x *Request) GetFm() *ForwardMsg {
	if x != nil {
		if x, ok := x.Msg.(*Request_Fm); ok {
			return x.Fm
		}
	}
	return nil
}

type isRequest_Msg interface {
	isRequest_Msg()
}

type Request_Empty struct {
	Empty *Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

type Request_Str struct {
	Str string `protobuf:"bytes,3,opt,name=str,proto3,oneof"`
}

type Request_Txt struct {
	Txt *TextMsg `protobuf:"bytes,4,opt,name=txt,proto3,oneof"`
}

type Request_File struct {
	File *PathMsg `protobuf:"bytes,5,opt,name=file,proto3,oneof"`
}

type Request_Query struct {
	Query *DbQuery `protobuf:"bytes,6,opt,name=query,proto3,oneof"`
}

type Request_V struct {
	V *Verification `protobuf:"bytes,7,opt,name=v,proto3,oneof"`
}

type Request_M struct {
	M *MemberMgmt `protobuf:"bytes,8,opt,name=m,proto3,oneof"` // 群成员管理，添加、删除、邀请
}

type Request_Xml struct {
	Xml *XmlMsg `protobuf:"bytes,9,opt,name=xml,proto3,oneof"`
}

type Request_Dec struct {
	Dec *DecPath `protobuf:"bytes,10,opt,name=dec,proto3,oneof"`
}

type Request_Tf struct {
	Tf *Transfer `protobuf:"bytes,11,opt,name=tf,proto3,oneof"`
}

type Request_Ui64 struct {
	Ui64 uint64 `protobuf:"varint,12,opt,name=ui64,proto3,oneof"` // 64 位整数，通用
}

type Request_Flag struct {
	Flag bool `protobuf:"varint,13,opt,name=flag,proto3,oneof"`
}

type Request_Att struct {
	Att *AttachMsg `protobuf:"bytes,14,opt,name=att,proto3,oneof"`
}

type Request_Am struct {
	Am *AudioMsg `protobuf:"bytes,15,opt,name=am,proto3,oneof"`
}

type Request_Rt struct {
	Rt *RichText `protobuf:"bytes,16,opt,name=rt,proto3,oneof"`
}

type Request_Pm struct {
	Pm *PatMsg `protobuf:"bytes,17,opt,name=pm,proto3,oneof"`
}

type Request_Fm struct {
	Fm *ForwardMsg `protobuf:"bytes,18,opt,name=fm,proto3,oneof"`
}

func (*Request_Empty) isRequest_Msg() {}

func (*Request_Str) isRequest_Msg() {}

func (*Request_Txt) isRequest_Msg() {}

func (*Request_File) isRequest_Msg() {}

func (*Request_Query) isRequest_Msg() {}

func (*Request_V) isRequest_Msg() {}

func (*Request_M) isRequest_Msg() {}

func (*Request_Xml) isRequest_Msg() {}

func (*Request_Dec) isRequest_Msg() {}

func (*Request_Tf) isRequest_Msg() {}

func (*Request_Ui64) isRequest_Msg() {}

func (*Request_Flag) isRequest_Msg() {}

func (*Request_Att) isRequest_Msg() {}

func (*Request_Am) isRequest_Msg() {}

func (*Request_Rt) isRequest_Msg() {}

func (*Request_Pm) isRequest_Msg() {}

func (*Request_Fm) isRequest_Msg() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Func  Functions              `protobuf:"varint,1,opt,name=func,proto3,enum=wcf.Functions" json:"func,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Response_Status
	//	*Response_Str
	//	*Response_Wxmsg
	//	*Response_Types
	//	*Response_Contacts
	//	*Response_Dbs
	//	*Response_Tables
	//	*Response_Rows
	//	*Response_Ui
	//	*Response_Ocr
	Msg           isResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetFunc() Functions {
	if x != nil {
		return x.Func
	}
	return Functions_FUNC_RESERVED
}

func (x *Response) GetMsg() isResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Response) GetStatus() int32 {
	if x != nil {
		if x, ok := x.Msg.(*Response_Status); ok {
			return x.Status
		}
	}
	return 0
}

func (x *Response) GetStr() string {
	if x != nil {
		if x, ok := x.Msg.(*Response_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Response) GetWxmsg() *WxMsg {
	if x != nil {
		if x, ok := x.Msg.(*Response_Wxmsg); ok {
			return x.Wxmsg
		}
	}
	return nil
}

func (x *Response) GetTypes() *MsgTypes {
	if x != nil {
		if x, ok := x.Msg.(*Response_Types); ok {
			return x.Types
		}
	}
	return nil
}

func (x *Response) GetContacts() *RpcContacts {
	if x != nil {
		if x, ok := x.Msg.(*Response_Contacts); ok {
			return x.Contacts
		}
	}
	return nil
}

func (x *Response) GetDbs() *DbNames {
	if x != nil {
		if x, ok := x.Msg.(*Response_Dbs); ok {
			return x.Dbs
		}
	}
	return nil
}

func (x *Response) GetTables() *DbTables {
	if x != nil {
		if x, ok := x.Msg.(*Response_Tables); ok {
			return x.Tables
		}
	}
	return nil
}

func (x *Response) GetRows() *DbRows {
	if x != nil {
		if x, ok := x.Msg.(*Response_Rows); ok {
			return x.Rows
		}
	}
	return nil
}

func (x *Response) GetUi() *UserInfo {
	if x != nil {
		if x, ok := x.Msg.(*Response_Ui); ok {
			return x.Ui
		}
	}
	return nil
}

func (x *Response) GetOcr() *OcrMsg {
	if x != nil {
		if x, ok := x.Msg.(*Response_Ocr); ok {
			return x.Ocr
		}
	}
	return nil
}

type isResponse_Msg interface {
	isResponse_Msg()
}

type Response_Status struct {
	Status int32 `protobuf:"varint,2,opt,name=status,proto3,oneof"` // Int 状态，通用
}

type Response_Str struct {
	Str string `protobuf:"bytes,3,opt,name=str,proto3,oneof"` // 字符串
}

type Response_Wxmsg struct {
	Wxmsg *WxMsg `protobuf:"bytes,4,opt,name=wxmsg,proto3,oneof"` // 微信消息
}

type Response_Types struct {
	Types *MsgTypes `protobuf:"bytes,5,opt,name=types,proto3,oneof"` // 消息类型
}

type Response_Contacts struct {
	Contacts *RpcContacts `protobuf:"bytes,6,opt,name=contacts,proto3,oneof"` // 联系人
}

type Response_Dbs struct {
	Dbs *DbNames `protobuf:"bytes,7,opt,name=dbs,proto3,oneof"` // 数据库列表
}

type Response_Tables struct {
	Tables *DbTables `protobuf:"bytes,8,opt,name=tables,proto3,oneof"` // 表列表
}

type Response_Rows struct {
	Rows *DbRows `protobuf:"bytes,9,opt,name=rows,proto3,oneof"` // 行列表
}

type Response_Ui struct {
	Ui *UserInfo `protobuf:"bytes,10,opt,name=ui,proto3,oneof"` // 个人信息
}

type Response_Ocr struct {
	Ocr *OcrMsg `protobuf:"bytes,11,opt,name=ocr,proto3,oneof"` // OCR 结果
}

func (*Response_Status) isResponse_Msg() {}

func (*Response_Str) isResponse_Msg() {}

func (*Response_Wxmsg) isResponse_Msg() {}

func (*Response_Types) isResponse_Msg() {}

func (*Response_Contacts) isResponse_Msg() {}

func (*Response_Dbs) isResponse_Msg() {}

func (*Response_Tables) isResponse_Msg() {}

func (*Response_Rows) isResponse_Msg() {}

func (*Response_Ui) isResponse_Msg() {}

func (*Response_Ocr) isResponse_Msg() {}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{2}
}

type WxMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSelf        bool                   `protobuf:"varint,1,opt,name=is_self,json=isSelf,proto3" json:"is_self,omitempty"`    // 是否自己发送的
	IsGroup       bool                   `protobuf:"varint,2,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"` // 是否群消息
	Id            uint64                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`                          // 消息 id
	Type          uint32                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                      // 消息类型
	Ts            uint32                 `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"`                          // 消息类型
	Roomid        string                 `protobuf:"bytes,6,opt,name=roomid,proto3" json:"roomid,omitempty"`                   // 群 id（如果是群消息的话）
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`                 // 消息内容
	Sender        string                 `protobuf:"bytes,8,opt,name=sender,proto3" json:"sender,omitempty"`                   // 消息发送者
	Sign          string                 `protobuf:"bytes,9,opt,name=sign,proto3" json:"sign,omitempty"`                       // Sign
	Thumb         string                 `protobuf:"bytes,10,opt,name=thumb,proto3" json:"thumb,omitempty"`                    // 缩略图
	Extra         string                 `protobuf:"bytes,11,opt,name=extra,proto3" json:"extra,omitempty"`                    // 附加内容
	Xml           string                 `protobuf:"bytes,12,opt,name=xml,proto3" json:"xml,omitempty"`                        // 消息 xml
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxMsg) Reset() {
	*x = WxMsg{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxMsg) ProtoMessage() {}

func (x *WxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxMsg.ProtoReflect.Descriptor instead.
func (*WxMsg) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{3}
}

func (x *WxMsg) GetIsSelf() bool {
	if x != nil {
		return x.IsSelf
	}
	return false
}

func (x *WxMsg) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *WxMsg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WxMsg) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *WxMsg) GetTs() uint32 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *WxMsg) GetRoomid() string {
	if x != nil {
		return x.Roomid
	}
	return ""
}

func (x *WxMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WxMsg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *WxMsg) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *WxMsg) GetThumb() string {
	if x != nil {
		return x.Thumb
	}
	return ""
}

func (x *WxMsg) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *WxMsg) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

type TextMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`           // 要发送的消息内容
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"` // 消息接收人，当为群时可@
	Aters         string                 `protobuf:"bytes,3,opt,name=aters,proto3" json:"aters,omitempty"`       // 要@的人列表，逗号分隔
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMsg) Reset() {
	*x = TextMsg{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMsg) ProtoMessage() {}

func (x *TextMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMsg.ProtoReflect.Descriptor instead.
func (*TextMsg) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{4}
}

func (x *TextMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TextMsg) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *TextMsg) GetAters() string {
	if x != nil {
		return x.Aters
	}
	return ""
}

type PathMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`         // 要发送的图片的路径
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"` // 消息接收人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathMsg) Reset() {
	*x = PathMsg{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathMsg) ProtoMessage() {}

func (x *PathMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathMsg.ProtoReflect.Descriptor instead.
func (*PathMsg) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{5}
}

func (x *PathMsg) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathMsg) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type XmlMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 消息接收人
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`   // xml 内容
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`         // 图片路径
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`        // 消息类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XmlMsg) Reset() {
	*x = XmlMsg{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XmlMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XmlMsg) ProtoMessage() {}

func (x *XmlMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XmlMsg.ProtoReflect.Descriptor instead.
func (*XmlMsg) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{6}
}

func (x *XmlMsg) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *XmlMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *XmlMsg) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *XmlMsg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type MsgTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         map[int32]string       `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgTypes) Reset() {
	*x = MsgTypes{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTypes) ProtoMessage() {}

func (x *MsgTypes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTypes.ProtoReflect.Descriptor instead.
func (*MsgTypes) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{7}
}

func (x *MsgTypes) GetTypes() map[int32]string {
	if x != nil {
		return x.Types
	}
	return nil
}

type RpcContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wxid          string                 `protobuf:"bytes,1,opt,name=wxid,proto3" json:"wxid,omitempty"`         // 微信 id
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`         // 微信号
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`     // 备注
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`         // 微信昵称
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`   // 国家
	Province      string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"` // 省/州
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`         // 城市
	Gender        int32                  `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`    // 性别
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcContact) Reset() {
	*x = RpcContact{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcContact) ProtoMessage() {}

func (x *RpcContact) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcContact.ProtoReflect.Descriptor instead.
func (*RpcContact) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{8}
}

func (x *RpcContact) GetWxid() string {
	if x != nil {
		return x.Wxid
	}
	return ""
}

func (x *RpcContact) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RpcContact) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RpcContact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RpcContact) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RpcContact) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *RpcContact) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *RpcContact) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type RpcContacts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*RpcContact          `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcContacts) Reset() {
	*x = RpcContacts{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcContacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcContacts) ProtoMessage() {}

func (x *RpcContacts) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcContacts.ProtoReflect.Descriptor instead.
func (*RpcContacts) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{9}
}

func (x *RpcContacts) GetContacts() []*RpcContact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type DbNames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbNames) Reset() {
	*x = DbNames{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbNames) ProtoMessage() {}

func (x *DbNames) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbNames.ProtoReflect.Descriptor instead.
func (*DbNames) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{10}
}

func (x *DbNames) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type DbTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 表名
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`   // 建表 SQL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbTable) Reset() {
	*x = DbTable{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbTable) ProtoMessage() {}

func (x *DbTable) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbTable.ProtoReflect.Descriptor instead.
func (*DbTable) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{11}
}

func (x *DbTable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DbTable) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type DbTables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*DbTable             `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbTables) Reset() {
	*x = DbTables{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbTables) ProtoMessage() {}

func (x *DbTables) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbTables.ProtoReflect.Descriptor instead.
func (*DbTables) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{12}
}

func (x *DbTables) GetTables() []*DbTable {
	if x != nil {
		return x.Tables
	}
	return nil
}

type DbQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Db            string                 `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`   // 目标数据库
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"` // 查询 SQL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbQuery) Reset() {
	*x = DbQuery{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbQuery) ProtoMessage() {}

func (x *DbQuery) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbQuery.ProtoReflect.Descriptor instead.
func (*DbQuery) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{13}
}

func (x *DbQuery) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *DbQuery) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type DbField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`      // 字段类型
	Column        string                 `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`   // 字段名称
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // 字段内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbField) Reset() {
	*x = DbField{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbField) ProtoMessage() {}

func (x *DbField) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbField.ProtoReflect.Descriptor instead.
func (*DbField) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{14}
}

func (x *DbField) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DbField) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *DbField) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type DbRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*DbField             `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbRow) Reset() {
	*x = DbRow{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbRow) ProtoMessage() {}

func (x *DbRow) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbRow.ProtoReflect.Descriptor instead.
func (*DbRow) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{15}
}

func (x *DbRow) GetFields() []*DbField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DbRows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*DbRow               `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbRows) Reset() {
	*x = DbRows{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbRows) ProtoMessage() {}

func (x *DbRows) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbRows.ProtoReflect.Descriptor instead.
func (*DbRows) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{16}
}

func (x *DbRows) GetRows() []*DbRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Verification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V3            string                 `protobuf:"bytes,1,opt,name=v3,proto3" json:"v3,omitempty"`        // 加密的用户名
	V4            string                 `protobuf:"bytes,2,opt,name=v4,proto3" json:"v4,omitempty"`        // Ticket
	Scene         int32                  `protobuf:"varint,3,opt,name=scene,proto3" json:"scene,omitempty"` // 添加方式：17 名片，30 扫码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verification) Reset() {
	*x = Verification{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verification) ProtoMessage() {}

func (x *Verification) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verification.ProtoReflect.Descriptor instead.
func (*Verification) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{17}
}

func (x *Verification) GetV3() string {
	if x != nil {
		return x.V3
	}
	return ""
}

func (x *Verification) GetV4() string {
	if x != nil {
		return x.V4
	}
	return ""
}

func (x *Verification) GetScene() int32 {
	if x != nil {
		return x.Scene
	}
	return 0
}

type MemberMgmt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roomid        string                 `protobuf:"bytes,1,opt,name=roomid,proto3" json:"roomid,omitempty"` // 要加的群ID
	Wxids         string                 `protobuf:"bytes,2,opt,name=wxids,proto3" json:"wxids,omitempty"`   // 要加群的人列表，逗号分隔
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberMgmt) Reset() {
	*x = MemberMgmt{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberMgmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberMgmt) ProtoMessage() {}

func (x *MemberMgmt) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberMgmt.ProtoReflect.Descriptor instead.
func (*MemberMgmt) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{18}
}

func (x *MemberMgmt) GetRoomid() string {
	if x != nil {
		return x.Roomid
	}
	return ""
}

func (x *MemberMgmt) GetWxids() string {
	if x != nil {
		return x.Wxids
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wxid          string                 `protobuf:"bytes,1,opt,name=wxid,proto3" json:"wxid,omitempty"`     // 微信ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`     // 昵称
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"` // 手机号
	Home          string                 `protobuf:"bytes,4,opt,name=home,proto3" json:"home,omitempty"`     // 文件/图片等父路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{19}
}

func (x *UserInfo) GetWxid() string {
	if x != nil {
		return x.Wxid
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserInfo) GetHome() string {
	if x != nil {
		return x.Home
	}
	return ""
}

type DecPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"` // 源路径
	Dst           string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"` // 目标路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecPath) Reset() {
	*x = DecPath{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecPath) ProtoMessage() {}

func (x *DecPath) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecPath.ProtoReflect.Descriptor instead.
func (*DecPath) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{20}
}

func (x *DecPath) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *DecPath) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wxid          string                 `protobuf:"bytes,1,opt,name=wxid,proto3" json:"wxid,omitempty"` // 转账人
	Tfid          string                 `protobuf:"bytes,2,opt,name=tfid,proto3" json:"tfid,omitempty"` // 转账id transferid
	Taid          string                 `protobuf:"bytes,3,opt,name=taid,proto3" json:"taid,omitempty"` // Transaction id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{21}
}

func (x *Transfer) GetWxid() string {
	if x != nil {
		return x.Wxid
	}
	return ""
}

func (x *Transfer) GetTfid() string {
	if x != nil {
		return x.Tfid
	}
	return ""
}

func (x *Transfer) GetTaid() string {
	if x != nil {
		return x.Taid
	}
	return ""
}

type AttachMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`      // 消息 id
	Thumb         string                 `protobuf:"bytes,2,opt,name=thumb,proto3" json:"thumb,omitempty"` // 消息中的 thumb
	Extra         string                 `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"` // 消息中的 extra
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachMsg) Reset() {
	*x = AttachMsg{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachMsg) ProtoMessage() {}

func (x *AttachMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachMsg.ProtoReflect.Descriptor instead.
func (*AttachMsg) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{22}
}

func (x *AttachMsg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttachMsg) GetThumb() string {
	if x != nil {
		return x.Thumb
	}
	return ""
}

func (x *AttachMsg) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type AudioMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`  // 语音消息 id
	Dir           string                 `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"` // 存放目录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioMsg) Reset() {
	*x = AudioMsg{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioMsg) ProtoMessage() {}

func (x *AudioMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioMsg.ProtoReflect.Descriptor instead.
func (*AudioMsg) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{23}
}

func (x *AudioMsg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioMsg) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type RichText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // 显示名字
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`   // 公众号 id
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`       // 标题
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`     // 摘要
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`           // 链接
	Thumburl      string                 `protobuf:"bytes,6,opt,name=thumburl,proto3" json:"thumburl,omitempty"` // 缩略图
	Receiver      string                 `protobuf:"bytes,7,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RichText) Reset() {
	*x = RichText{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RichText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichText) ProtoMessage() {}

func (x *RichText) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichText.ProtoReflect.Descriptor instead.
func (*RichText) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{24}
}

func (x *RichText) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RichText) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RichText) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RichText) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *RichText) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RichText) GetThumburl() string {
	if x != nil {
		return x.Thumburl
	}
	return ""
}

func (x *RichText) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type PatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roomid        string                 `protobuf:"bytes,1,opt,name=roomid,proto3" json:"roomid,omitempty"` // 群 id
	Wxid          string                 `protobuf:"bytes,2,opt,name=wxid,proto3" json:"wxid,omitempty"`     // wxid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatMsg) Reset() {
	*x = PatMsg{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatMsg) ProtoMessage() {}

func (x *PatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatMsg.ProtoReflect.Descriptor instead.
func (*PatMsg) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{25}
}

func (x *PatMsg) GetRoomid() string {
	if x != nil {
		return x.Roomid
	}
	return ""
}

func (x *PatMsg) GetWxid() string {
	if x != nil {
		return x.Wxid
	}
	return ""
}

type OcrMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`  // 结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrMsg) Reset() {
	*x = OcrMsg{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrMsg) ProtoMessage() {}

func (x *OcrMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrMsg.ProtoReflect.Descriptor instead.
func (*OcrMsg) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{26}
}

func (x *OcrMsg) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OcrMsg) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ForwardMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            // 待转发消息 ID
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"` // 转发接收目标，群为 roomId，个人为 wxid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardMsg) Reset() {
	*x = ForwardMsg{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMsg) ProtoMessage() {}

func (x *ForwardMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMsg.ProtoReflect.Descriptor instead.
func (*ForwardMsg) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{27}
}

func (x *ForwardMsg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ForwardMsg) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type RoomData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomData) Reset() {
	*x = RoomData{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomData) ProtoMessage() {}

func (x *RoomData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomData.ProtoReflect.Descriptor instead.
func (*RoomData) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{28}
}

func (x *RoomData) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wxid          string                 `protobuf:"bytes,1,opt,name=wxid,proto3" json:"wxid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_grpc_proto_wcf_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_wcf_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_grpc_proto_wcf_proto_rawDescGZIP(), []int{29}
}

func (x *Member) GetWxid() string {
	if x != nil {
		return x.Wxid
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_grpc_proto_wcf_proto protoreflect.FileDescriptor

const file_grpc_proto_wcf_proto_rawDesc = "" +
	"\n" +
	"\x14grpc/proto/wcf.proto\x12\x03wcf\"\xd4\x04\n" +
	"\aRequest\x12\"\n" +
	"\x04func\x18\x01 \x01(\x0e2\x0e.wcf.FunctionsR\x04func\x12\"\n" +
	"\x05empty\x18\x02 \x01(\v2\n" +
	".wcf.EmptyH\x00R\x05empty\x12\x12\n" +
	"\x03str\x18\x03 \x01(\tH\x00R\x03str\x12 \n" +
	"\x03txt\x18\x04 \x01(\v2\f.wcf.TextMsgH\x00R\x03txt\x12\"\n" +
	"\x04file\x18\x05 \x01(\v2\f.wcf.PathMsgH\x00R\x04file\x12$\n" +
	"\x05query\x18\x06 \x01(\v2\f.wcf.DbQueryH\x00R\x05query\x12!\n" +
	"\x01v\x18\a \x01(\v2\x11.wcf.VerificationH\x00R\x01v\x12\x1f\n" +
	"\x01m\x18\b \x01(\v2\x0f.wcf.MemberMgmtH\x00R\x01m\x12\x1f\n" +
	"\x03xml\x18\t \x01(\v2\v.wcf.XmlMsgH\x00R\x03xml\x12 \n" +
	"\x03dec\x18\n" +
	" \x01(\v2\f.wcf.DecPathH\x00R\x03dec\x12\x1f\n" +
	"\x02tf\x18\v \x01(\v2\r.wcf.TransferH\x00R\x02tf\x12\x14\n" +
	"\x04ui64\x18\f \x01(\x04H\x00R\x04ui64\x12\x14\n" +
	"\x04flag\x18\r \x01(\bH\x00R\x04flag\x12\"\n" +
	"\x03att\x18\x0e \x01(\v2\x0e.wcf.AttachMsgH\x00R\x03att\x12\x1f\n" +
	"\x02am\x18\x0f \x01(\v2\r.wcf.AudioMsgH\x00R\x02am\x12\x1f\n" +
	"\x02rt\x18\x10 \x01(\v2\r.wcf.RichTextH\x00R\x02rt\x12\x1d\n" +
	"\x02pm\x18\x11 \x01(\v2\v.wcf.PatMsgH\x00R\x02pm\x12!\n" +
	"\x02fm\x18\x12 \x01(\v2\x0f.wcf.ForwardMsgH\x00R\x02fmB\x05\n" +
	"\x03msg\"\x8e\x03\n" +
	"\bResponse\x12\"\n" +
	"\x04func\x18\x01 \x01(\x0e2\x0e.wcf.FunctionsR\x04func\x12\x18\n" +
	"\x06status\x18\x02 \x01(\x05H\x00R\x06status\x12\x12\n" +
	"\x03str\x18\x03 \x01(\tH\x00R\x03str\x12\"\n" +
	"\x05wxmsg\x18\x04 \x01(\v2\n" +
	".wcf.WxMsgH\x00R\x05wxmsg\x12%\n" +
	"\x05types\x18\x05 \x01(\v2\r.wcf.MsgTypesH\x00R\x05types\x12.\n" +
	"\bcontacts\x18\x06 \x01(\v2\x10.wcf.RpcContactsH\x00R\bcontacts\x12 \n" +
	"\x03dbs\x18\a \x01(\v2\f.wcf.DbNamesH\x00R\x03dbs\x12'\n" +
	"\x06tables\x18\b \x01(\v2\r.wcf.DbTablesH\x00R\x06tables\x12!\n" +
	"\x04rows\x18\t \x01(\v2\v.wcf.DbRowsH\x00R\x04rows\x12\x1f\n" +
	"\x02ui\x18\n" +
	" \x01(\v2\r.wcf.UserInfoH\x00R\x02ui\x12\x1f\n" +
	"\x03ocr\x18\v \x01(\v2\v.wcf.OcrMsgH\x00R\x03ocrB\x05\n" +
	"\x03msg\"\a\n" +
	"\x05Empty\"\x8b\x02\n" +
	"\x05WxMsg\x12\x17\n" +
	"\ais_self\x18\x01 \x01(\bR\x06isSelf\x12\x19\n" +
	"\bis_group\x18\x02 \x01(\bR\aisGroup\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x04 \x01(\rR\x04type\x12\x0e\n" +
	"\x02ts\x18\x05 \x01(\rR\x02ts\x12\x16\n" +
	"\x06roomid\x18\x06 \x01(\tR\x06roomid\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x16\n" +
	"\x06sender\x18\b \x01(\tR\x06sender\x12\x12\n" +
	"\x04sign\x18\t \x01(\tR\x04sign\x12\x14\n" +
	"\x05thumb\x18\n" +
	" \x01(\tR\x05thumb\x12\x14\n" +
	"\x05extra\x18\v \x01(\tR\x05extra\x12\x10\n" +
	"\x03xml\x18\f \x01(\tR\x03xml\"M\n" +
	"\aTextMsg\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x14\n" +
	"\x05aters\x18\x03 \x01(\tR\x05aters\"9\n" +
	"\aPathMsg\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\"f\n" +
	"\x06XmlMsg\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\"t\n" +
	"\bMsgTypes\x12.\n" +
	"\x05types\x18\x01 \x03(\v2\x18.wcf.MsgTypes.TypesEntryR\x05types\x1a8\n" +
	"\n" +
	"TypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x01\n" +
	"\n" +
	"RpcContact\x12\x12\n" +
	"\x04wxid\x18\x01 \x01(\tR\x04wxid\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x16\n" +
	"\x06gender\x18\b \x01(\x05R\x06gender\":\n" +
	"\vRpcContacts\x12+\n" +
	"\bcontacts\x18\x01 \x03(\v2\x0f.wcf.RpcContactR\bcontacts\"\x1f\n" +
	"\aDbNames\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"/\n" +
	"\aDbTable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\"0\n" +
	"\bDbTables\x12$\n" +
	"\x06tables\x18\x01 \x03(\v2\f.wcf.DbTableR\x06tables\"+\n" +
	"\aDbQuery\x12\x0e\n" +
	"\x02db\x18\x01 \x01(\tR\x02db\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\"O\n" +
	"\aDbField\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x16\n" +
	"\x06column\x18\x02 \x01(\tR\x06column\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"-\n" +
	"\x05DbRow\x12$\n" +
	"\x06fields\x18\x01 \x03(\v2\f.wcf.DbFieldR\x06fields\"(\n" +
	"\x06DbRows\x12\x1e\n" +
	"\x04rows\x18\x01 \x03(\v2\n" +
	".wcf.DbRowR\x04rows\"D\n" +
	"\fVerification\x12\x0e\n" +
	"\x02v3\x18\x01 \x01(\tR\x02v3\x12\x0e\n" +
	"\x02v4\x18\x02 \x01(\tR\x02v4\x12\x14\n" +
	"\x05scene\x18\x03 \x01(\x05R\x05scene\":\n" +
	"\n" +
	"MemberMgmt\x12\x16\n" +
	"\x06roomid\x18\x01 \x01(\tR\x06roomid\x12\x14\n" +
	"\x05wxids\x18\x02 \x01(\tR\x05wxids\"^\n" +
	"\bUserInfo\x12\x12\n" +
	"\x04wxid\x18\x01 \x01(\tR\x04wxid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04home\x18\x04 \x01(\tR\x04home\"-\n" +
	"\aDecPath\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\"F\n" +
	"\bTransfer\x12\x12\n" +
	"\x04wxid\x18\x01 \x01(\tR\x04wxid\x12\x12\n" +
	"\x04tfid\x18\x02 \x01(\tR\x04tfid\x12\x12\n" +
	"\x04taid\x18\x03 \x01(\tR\x04taid\"G\n" +
	"\tAttachMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05thumb\x18\x02 \x01(\tR\x05thumb\x12\x14\n" +
	"\x05extra\x18\x03 \x01(\tR\x05extra\",\n" +
	"\bAudioMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03dir\x18\x02 \x01(\tR\x03dir\"\xb0\x01\n" +
	"\bRichText\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1a\n" +
	"\bthumburl\x18\x06 \x01(\tR\bthumburl\x12\x1a\n" +
	"\breceiver\x18\a \x01(\tR\breceiver\"4\n" +
	"\x06PatMsg\x12\x16\n" +
	"\x06roomid\x18\x01 \x01(\tR\x06roomid\x12\x12\n" +
	"\x04wxid\x18\x02 \x01(\tR\x04wxid\"8\n" +
	"\x06OcrMsg\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\"8\n" +
	"\n" +
	"ForwardMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\"1\n" +
	"\bRoomData\x12%\n" +
	"\amembers\x18\x01 \x03(\v2\v.wcf.MemberR\amembers\"0\n" +
	"\x06Member\x12\x12\n" +
	"\x04wxid\x18\x01 \x01(\tR\x04wxid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name*\xd9\x05\n" +
	"\tFunctions\x12\x11\n" +
	"\rFUNC_RESERVED\x10\x00\x12\x11\n" +
	"\rFUNC_IS_LOGIN\x10\x01\x12\x16\n" +
	"\x12FUNC_GET_SELF_WXID\x10\x10\x12\x16\n" +
	"\x12FUNC_GET_MSG_TYPES\x10\x11\x12\x15\n" +
	"\x11FUNC_GET_CONTACTS\x10\x12\x12\x15\n" +
	"\x11FUNC_GET_DB_NAMES\x10\x13\x12\x16\n" +
	"\x12FUNC_GET_DB_TABLES\x10\x14\x12\x16\n" +
	"\x12FUNC_GET_USER_INFO\x10\x15\x12\x16\n" +
	"\x12FUNC_GET_AUDIO_MSG\x10\x16\x12\x11\n" +
	"\rFUNC_SEND_TXT\x10 \x12\x11\n" +
	"\rFUNC_SEND_IMG\x10!\x12\x12\n" +
	"\x0eFUNC_SEND_FILE\x10\"\x12\x11\n" +
	"\rFUNC_SEND_XML\x10#\x12\x15\n" +
	"\x11FUNC_SEND_EMOTION\x10$\x12\x16\n" +
	"\x12FUNC_SEND_RICH_TXT\x10%\x12\x15\n" +
	"\x11FUNC_SEND_PAT_MSG\x10&\x12\x14\n" +
	"\x10FUNC_FORWARD_MSG\x10'\x12\x18\n" +
	"\x14FUNC_ENABLE_RECV_TXT\x100\x12\x19\n" +
	"\x15FUNC_DISABLE_RECV_TXT\x10@\x12\x16\n" +
	"\x12FUNC_EXEC_DB_QUERY\x10P\x12\x16\n" +
	"\x12FUNC_ACCEPT_FRIEND\x10Q\x12\x16\n" +
	"\x12FUNC_RECV_TRANSFER\x10R\x12\x14\n" +
	"\x10FUNC_REFRESH_PYQ\x10S\x12\x18\n" +
	"\x14FUNC_DOWNLOAD_ATTACH\x10T\x12\x19\n" +
	"\x15FUNC_GET_CONTACT_INFO\x10U\x12\x13\n" +
	"\x0fFUNC_REVOKE_MSG\x10V\x12\x16\n" +
	"\x12FUNC_DECRYPT_IMAGE\x10`\x12\x11\n" +
	"\rFUNC_EXEC_OCR\x10a\x12\x19\n" +
	"\x15FUNC_ADD_ROOM_MEMBERS\x10p\x12\x19\n" +
	"\x15FUNC_DEL_ROOM_MEMBERS\x10q\x12\x19\n" +
	"\x15FUNC_INV_ROOM_MEMBERS\x10rB\x15\n" +
	"\vcom.iamteerZ\x06../wcfb\x06proto3"

var (
	file_grpc_proto_wcf_proto_rawDescOnce sync.Once
	file_grpc_proto_wcf_proto_rawDescData []byte
)

func file_grpc_proto_wcf_proto_rawDescGZIP() []byte {
	file_grpc_proto_wcf_proto_rawDescOnce.Do(func() {
		file_grpc_proto_wcf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_wcf_proto_rawDesc), len(file_grpc_proto_wcf_proto_rawDesc)))
	})
	return file_grpc_proto_wcf_proto_rawDescData
}

var file_grpc_proto_wcf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_proto_wcf_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_grpc_proto_wcf_proto_goTypes = []any{
	(Functions)(0),       // 0: wcf.Functions
	(*Request)(nil),      // 1: wcf.Request
	(*Response)(nil),     // 2: wcf.Response
	(*Empty)(nil),        // 3: wcf.Empty
	(*WxMsg)(nil),        // 4: wcf.WxMsg
	(*TextMsg)(nil),      // 5: wcf.TextMsg
	(*PathMsg)(nil),      // 6: wcf.PathMsg
	(*XmlMsg)(nil),       // 7: wcf.XmlMsg
	(*MsgTypes)(nil),     // 8: wcf.MsgTypes
	(*RpcContact)(nil),   // 9: wcf.RpcContact
	(*RpcContacts)(nil),  // 10: wcf.RpcContacts
	(*DbNames)(nil),      // 11: wcf.DbNames
	(*DbTable)(nil),      // 12: wcf.DbTable
	(*DbTables)(nil),     // 13: wcf.DbTables
	(*DbQuery)(nil),      // 14: wcf.DbQuery
	(*DbField)(nil),      // 15: wcf.DbField
	(*DbRow)(nil),        // 16: wcf.DbRow
	(*DbRows)(nil),       // 17: wcf.DbRows
	(*Verification)(nil), // 18: wcf.Verification
	(*MemberMgmt)(nil),   // 19: wcf.MemberMgmt
	(*UserInfo)(nil),     // 20: wcf.UserInfo
	(*DecPath)(nil),      // 21: wcf.DecPath
	(*Transfer)(nil),     // 22: wcf.Transfer
	(*AttachMsg)(nil),    // 23: wcf.AttachMsg
	(*AudioMsg)(nil),     // 24: wcf.AudioMsg
	(*RichText)(nil),     // 25: wcf.RichText
	(*PatMsg)(nil),       // 26: wcf.PatMsg
	(*OcrMsg)(nil),       // 27: wcf.OcrMsg
	(*ForwardMsg)(nil),   // 28: wcf.ForwardMsg
	(*RoomData)(nil),     // 29: wcf.RoomData
	(*Member)(nil),       // 30: wcf.Member
	nil,                  // 31: wcf.MsgTypes.TypesEntry
}
var file_grpc_proto_wcf_proto_depIdxs = []int32{
	0,  // 0: wcf.Request.func:type_name -> wcf.Functions
	3,  // 1: wcf.Request.empty:type_name -> wcf.Empty
	5,  // 2: wcf.Request.txt:type_name -> wcf.TextMsg
	6,  // 3: wcf.Request.file:type_name -> wcf.PathMsg
	14, // 4: wcf.Request.query:type_name -> wcf.DbQuery
	18, // 5: wcf.Request.v:type_name -> wcf.Verification
	19, // 6: wcf.Request.m:type_name -> wcf.MemberMgmt
	7,  // 7: wcf.Request.xml:type_name -> wcf.XmlMsg
	21, // 8: wcf.Request.dec:type_name -> wcf.DecPath
	22, // 9: wcf.Request.tf:type_name -> wcf.Transfer
	23, // 10: wcf.Request.att:type_name -> wcf.AttachMsg
	24, // 11: wcf.Request.am:type_name -> wcf.AudioMsg
	25, // 12: wcf.Request.rt:type_name -> wcf.RichText
	26, // 13: wcf.Request.pm:type_name -> wcf.PatMsg
	28, // 14: wcf.Request.fm:type_name -> wcf.ForwardMsg
	0,  // 15: wcf.Response.func:type_name -> wcf.Functions
	4,  // 16: wcf.Response.wxmsg:type_name -> wcf.WxMsg
	8,  // 17: wcf.Response.types:type_name -> wcf.MsgTypes
	10, // 18: wcf.Response.contacts:type_name -> wcf.RpcContacts
	11, // 19: wcf.Response.dbs:type_name -> wcf.DbNames
	13, // 20: wcf.Response.tables:type_name -> wcf.DbTables
	17, // 21: wcf.Response.rows:type_name -> wcf.DbRows
	20, // 22: wcf.Response.ui:type_name -> wcf.UserInfo
	27, // 23: wcf.Response.ocr:type_name -> wcf.OcrMsg
	31, // 24: wcf.MsgTypes.types:type_name -> wcf.MsgTypes.TypesEntry
	9,  // 25: wcf.RpcContacts.contacts:type_name -> wcf.RpcContact
	12, // 26: wcf.DbTables.tables:type_name -> wcf.DbTable
	15, // 27: wcf.DbRow.fields:type_name -> wcf.DbField
	16, // 28: wcf.DbRows.rows:type_name -> wcf.DbRow
	30, // 29: wcf.RoomData.members:type_name -> wcf.Member
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_grpc_proto_wcf_proto_init() }
func file_grpc_proto_wcf_proto_init() {
	if File_grpc_proto_wcf_proto != nil {
		return
	}
	file_grpc_proto_wcf_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Empty)(nil),
		(*Request_Str)(nil),
		(*Request_Txt)(nil),
		(*Request_File)(nil),
		(*Request_Query)(nil),
		(*Request_V)(nil),
		(*Request_M)(nil),
		(*Request_Xml)(nil),
		(*Request_Dec)(nil),
		(*Request_Tf)(nil),
		(*Request_Ui64)(nil),
		(*Request_Flag)(nil),
		(*Request_Att)(nil),
		(*Request_Am)(nil),
		(*Request_Rt)(nil),
		(*Request_Pm)(nil),
		(*Request_Fm)(nil),
	}
	file_grpc_proto_wcf_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_Status)(nil),
		(*Response_Str)(nil),
		(*Response_Wxmsg)(nil),
		(*Response_Types)(nil),
		(*Response_Contacts)(nil),
		(*Response_Dbs)(nil),
		(*Response_Tables)(nil),
		(*Response_Rows)(nil),
		(*Response_Ui)(nil),
		(*Response_Ocr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_wcf_proto_rawDesc), len(file_grpc_proto_wcf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_proto_wcf_proto_goTypes,
		DependencyIndexes: file_grpc_proto_wcf_proto_depIdxs,
		EnumInfos:         file_grpc_proto_wcf_proto_enumTypes,
		MessageInfos:      file_grpc_proto_wcf_proto_msgTypes,
	}.Build()
	File_grpc_proto_wcf_proto = out.File
	file_grpc_proto_wcf_proto_goTypes = nil
	file_grpc_proto_wcf_proto_depIdxs = nil
}
